# Introduction to Numpy
Learning Numpy!

In [2]:
import numpy as np
np.__version__

'1.15.4'

## Differences between lists and NumPy Arrays
- An array's size is immutable. You cannot append, insert, or remove elements, like you can with a list.
- All of an array's elements must be of the same data type. 
- A NumPy array behaves in a pythonic fashion. You can len(my_array) just like you would assume.

In [3]:
gpas_as_list = [4.0, 3.286, 3.5]

In [14]:
# Can have elements appended to it.
gpas_as_list.append(4.0)
# Can have multiple data types
gpas_as_list.insert(1, "whatevs")
gpas_as_list.pop(1)

'whatevs'

In [15]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0, 4.0, 4.0]

In [7]:
gpas = np.array(gpas_as_list)

In [9]:
?gpas

## Indexing NumPy Arrays

### ---Retrieve Item Size

In [10]:
gpas.itemsize


8

In [11]:
gpas.size

5

In [12]:
len(gpas)

5

In [13]:
gpas.nbytes

40

### ---Generate practice data with random() function

In [8]:
rand_array = np.random.RandomState(43)
rand_log = rand_array.randint(30, 180, size=100, dtype=np.uint16)
rand_log

array([ 98, 146,  94,  80,  79, 118,  51,  67,  88,  51,  46,  81,  46,
       175, 121,  64, 140, 162, 166, 117, 167,  94,  65, 139, 157, 100,
       153,  70,  57, 119, 112, 141,  64,  63, 105, 174, 135, 147, 162,
       101,  66, 179, 114, 147,  89,  62, 148,  90,  73, 142, 114, 103,
        78, 123, 150, 119,  58,  54, 103,  59, 165,  91, 145, 114,  77,
        60, 134, 150,  33, 103, 135,  68,  49, 110,  45, 148,  65,  51,
       137, 171, 104,  57,  37, 149,  91, 170, 129, 148, 112,  81, 110,
        33, 136, 103,  82, 147, 176,  48,  53, 143], dtype=uint16)

## Indexing Boolean Arrays

In [9]:
rand_log < 60

array([False, False, False, False, False, False,  True, False, False,
        True,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True,  True,
       False])

### ---Fancy indexing with a boolean array 
Using a boolean array index is orders of magnitude faster than using a for loop. 

In [14]:
rand_log[rand_log < 60]

array([51, 51, 46, 46, 57, 58, 54, 59, 33, 49, 45, 51, 57, 37, 33, 48, 53],
      dtype=uint16)

### --- Using boolean expressions to index an array

Make sure to use ampersand instead of typing out 'and'

In [15]:
np.array([False, True, True]) & np.array([True, False, True])

array([False, False,  True])

In [19]:
rand_log[(rand_log < 60) & (rand_log > 0)] 

array([51, 51, 46, 46, 57, 58, 54, 59, 33, 49, 45, 51, 57, 37, 33, 48, 53],
      dtype=uint16)

## Slicing Practice
In Python, slices don't return a copy; they return a view of the data
A <b>view</b> references the same value in memory

In [20]:
flowers = ["daisy", "rose", "tulip", "daffodil", "orchid", "sunflower"]
flowers[1:3]

['rose', 'tulip']

In [22]:
flowers[:-1]

['daisy', 'rose', 'tulip', 'daffodil', 'orchid']

In [29]:
practice = np.arange(42)
practice.shape = (7,6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [30]:
practice[2,1]

13

In [31]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
practice[2:4, 3::2]      #two colons skips over selected columns

array([[15, 17],
       [21, 23]])

In [33]:
practice.base is None

True

In [34]:
practice.flags['OWNDATA']

True

## Linear Algebra 
<ul>
    <li>There is a module for linear algebra, <a href="https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.linalg.html">linalg</a></li>
    <li>You can solve for a syste of equations using the solve() function</li>
        <ul><li>You can create a square 2D matrix and a constant row vector and solve for each variable column</li>
            <li>You can double check the answer using the inner product or dot() function.</li>
        </ul>
    <li>You can use the <code>@</code> to produce the dot product of two arrays.</li>
</ul>
    

In [7]:
orders = np.array([
    [2, 0, 0, 0],
    [4, 1, 2, 2], 
    [0, 1, 0, 1],
    [6, 0, 1, 2]
])
totals = np.array([3, 20.50, 10, 14.25])

In [8]:
prices = np.linalg.solve(orders, totals)
prices

array([1.5 , 8.  , 1.25, 2.  ])

In [13]:
# A • B

orders @ prices

array([ 3.  , 20.5 , 10.  , 14.25])

In [11]:
orders.dot(prices)

array([ 3.  , 20.5 , 10.  , 14.25])

### Vector math with NumPy

In [19]:
a, b = np.split(np.arange(1,11), 2)
a, b


(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [20]:
a + b

array([ 7,  9, 11, 13, 15])

In [21]:
a - b

array([-5, -5, -5, -5, -5])

In [22]:
b - a 

array([5, 5, 5, 5, 5])

In [23]:
a * b

array([ 6, 14, 24, 36, 50])

In [24]:
a + 2

array([3, 4, 5, 6, 7])

## Universal Functions
<ul>
    <li><a href="https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html">ufuncs</a> are commonly needed vectorized functions</li>
    <ul><li>Vectorized functions allow you to operate element by element without using a loop.</li></ul> 
    <li>The standard math and comparison operators have all been overloaded sothat they can make use of vectorization.</li>
    <li>Values can be <a href="https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html#broadcasting">broadcasted</a>, or stretched to be applied to the ufunc.